summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-15.0-x86_64/releases/download/2025.03.12/pkg-config-0.29.2-MacOSX-15.0-x86_64.release.tar.xz
bin-sha: 70622c14063509bd0e32418e7e4b5bba4dec35d5783f0012d56d7ce8fd691cd9
